# Copyright (c) 2026 webAI, Inc.

PYTHON ?= python3

.PHONY: install install-dev lint format test check pre-commit-install pre-commit-run clean

install:
	$(PYTHON) -m pip install -e .

install-dev:
	$(PYTHON) -m pip install -e .[dev]

lint:
	$(PYTHON) -m ruff check src tests
	$(PYTHON) -m ruff format --check src tests

format:
	$(PYTHON) -m ruff check --fix src tests
	$(PYTHON) -m ruff format src tests

test:
	$(PYTHON) -m pytest

check: lint test

pre-commit-install:
	$(PYTHON) -m pre_commit install

pre-commit-run:
	$(PYTHON) -m pre_commit run --all-files

# Remove all build artifacts, caches, and runtime-download scratch dirs.
# Safe to run any time — every removed path is either auto-regenerated by
# build/install/test tooling or auto-redownloaded by the trainer/scripts.
clean:
	@echo "Removing build / packaging artifacts..."
	rm -rf build/ dist/ src/*.egg-info/
	@echo "Removing Python bytecode caches..."
	find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	find . -type f -name '*.pyc' -delete
	@echo "Removing tool caches..."
	rm -rf .pytest_cache/ .ruff_cache/ .mypy_cache/
	@echo "Removing runtime download / output dirs (datasets/ models/ runs/ results/ images/)..."
	rm -rf datasets/ models/ runs/ results/ images/
	@echo "Removing macOS metadata files..."
	find . -type f -name '.DS_Store' -delete
	@echo "Done."
